/**
 * Compatibility entry point. Challenge contracts live in contracts.ts so every active
 * renderer and validator uses the discriminated scored/explore model.
 */
export type {
  ChallengeAnswer,
  ChallengeChoice,
  ChallengeDifficulty,
  ChallengeEvaluation,
  ChallengeEvidence,
  ChallengeHint,
  ChallengeLifecycle,
  ChallengeMode,
  ChallengePayload,
  ChallengeReturnRecord,
  ChallengeScoring,
  ChallengeSpec,
  ChallengeType,
  ConceptMatchChallenge,
  EvidenceHuntChallenge,
  EvidenceHuntPayload,
  EvolutionChallenge,
  EvolutionPayload,
  FigureBuildChallenge,
  FigureBuildPayload,
  FigureDetectiveChallenge,
  FigureDetectivePayload,
  ExploreChallenge,
  GenerationMetadata,
  GroundedRelationship,
  LearnerResponse,
  MultipleChoiceChallenge,
  OrderingChallenge,
  PaperCheckChallenge,
  PaperCheckPayload,
  PaperVsPaperChallenge,
  PaperVsPaperPayload,
  PredictionChallenge,
  PredictionPayload,
  ClaimEvidenceChallenge,
  ClaimEvidencePayload,
  ScoredChallenge,
  TimelineChallenge,
  TimelinePayload,
} from "./contracts";
